import Variants from '../types/variants';

const SIZES = [
  'auto',
  'px',
  '0',
  'min',
  'max',
  'fit',
  '2',
  '4',
  '8',
  '12',
  '16',
  '20',
  '24',
  '32',
  '40',
  '48',
  '56',
  '64',
  '80',
  '96',
  '120',
  '160',
  '200',
  '240',
  '280',
  '320',
  '360',
  '440',
  '520',
  '640',
  '720',
  '800',
  '960',
  '1/12',
  '2/12',
  '3/12',
  '4/12',
  '5/12',
  '6/12',
  '7/12',
  '8/12',
  '9/12',
  '10/12',
  '11/12',
  'full',
];

const sizing = {
  width: {
    class: 'w',
    responsive: true,
    values: [...SIZES, 'screen', 'svw', 'dvw', 'lvw'] as const,
  },
  minWidth: {
    class: 'min-w',
    responsive: true,
    values: [...SIZES, 'screen', 'svw', 'dvw', 'lvw'] as const,
  },
  maxWidth: {
    class: 'max-w',
    responsive: true,
    values: [...SIZES, 'screen', 'svw', 'dvw', 'lvw'] as const,
  },
  height: {
    class: 'h',
    responsive: true,
    values: [...SIZES, 'screen', 'svh', 'dvh', 'lvh'] as const,
  },
  minHeight: {
    class: 'min-h',
    responsive: true,
    values: [...SIZES, 'screen', 'svh', 'dvh', 'lvh'] as const,
  },
  maxHeight: {
    class: 'max-h',
    responsive: true,
    values: [...SIZES, 'screen', 'svh', 'dvh', 'lvh'] as const,
  },
} satisfies Variants.Map;

export default sizing;
